package cn.ml.saddhu.bihudaily.engine.domain;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.ml.saddhu.bihudaily.engine.domain.Creative;
import cn.ml.saddhu.bihudaily.engine.domain.Story;
import cn.ml.saddhu.bihudaily.engine.domain.Theme;
import cn.ml.saddhu.bihudaily.engine.domain.TopStory;
import cn.ml.saddhu.bihudaily.engine.domain.UserInfo;

import cn.ml.saddhu.bihudaily.engine.domain.CreativeDao;
import cn.ml.saddhu.bihudaily.engine.domain.StoryDao;
import cn.ml.saddhu.bihudaily.engine.domain.ThemeDao;
import cn.ml.saddhu.bihudaily.engine.domain.TopStoryDao;
import cn.ml.saddhu.bihudaily.engine.domain.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig creativeDaoConfig;
    private final DaoConfig storyDaoConfig;
    private final DaoConfig themeDaoConfig;
    private final DaoConfig topStoryDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final CreativeDao creativeDao;
    private final StoryDao storyDao;
    private final ThemeDao themeDao;
    private final TopStoryDao topStoryDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        creativeDaoConfig = daoConfigMap.get(CreativeDao.class).clone();
        creativeDaoConfig.initIdentityScope(type);

        storyDaoConfig = daoConfigMap.get(StoryDao.class).clone();
        storyDaoConfig.initIdentityScope(type);

        themeDaoConfig = daoConfigMap.get(ThemeDao.class).clone();
        themeDaoConfig.initIdentityScope(type);

        topStoryDaoConfig = daoConfigMap.get(TopStoryDao.class).clone();
        topStoryDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        creativeDao = new CreativeDao(creativeDaoConfig, this);
        storyDao = new StoryDao(storyDaoConfig, this);
        themeDao = new ThemeDao(themeDaoConfig, this);
        topStoryDao = new TopStoryDao(topStoryDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(Creative.class, creativeDao);
        registerDao(Story.class, storyDao);
        registerDao(Theme.class, themeDao);
        registerDao(TopStory.class, topStoryDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        creativeDaoConfig.clearIdentityScope();
        storyDaoConfig.clearIdentityScope();
        themeDaoConfig.clearIdentityScope();
        topStoryDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public CreativeDao getCreativeDao() {
        return creativeDao;
    }

    public StoryDao getStoryDao() {
        return storyDao;
    }

    public ThemeDao getThemeDao() {
        return themeDao;
    }

    public TopStoryDao getTopStoryDao() {
        return topStoryDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
