package cn.ml.saddhu.bihudaily.engine.domain;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.ml.saddhu.bihudaily.engine.domain.Creative;
import cn.ml.saddhu.bihudaily.engine.domain.Story;
import cn.ml.saddhu.bihudaily.engine.domain.Theme;
import cn.ml.saddhu.bihudaily.engine.domain.TopStory;
import cn.ml.saddhu.bihudaily.engine.domain.UserInfo;
import cn.ml.saddhu.bihudaily.engine.domain.Section;
import cn.ml.saddhu.bihudaily.engine.domain.StoryDetail;
import cn.ml.saddhu.bihudaily.engine.domain.ReadHistory;

import cn.ml.saddhu.bihudaily.engine.domain.CreativeDao;
import cn.ml.saddhu.bihudaily.engine.domain.StoryDao;
import cn.ml.saddhu.bihudaily.engine.domain.ThemeDao;
import cn.ml.saddhu.bihudaily.engine.domain.TopStoryDao;
import cn.ml.saddhu.bihudaily.engine.domain.UserInfoDao;
import cn.ml.saddhu.bihudaily.engine.domain.SectionDao;
import cn.ml.saddhu.bihudaily.engine.domain.StoryDetailDao;
import cn.ml.saddhu.bihudaily.engine.domain.ReadHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig creativeDaoConfig;
    private final DaoConfig storyDaoConfig;
    private final DaoConfig themeDaoConfig;
    private final DaoConfig topStoryDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig sectionDaoConfig;
    private final DaoConfig storyDetailDaoConfig;
    private final DaoConfig readHistoryDaoConfig;

    private final CreativeDao creativeDao;
    private final StoryDao storyDao;
    private final ThemeDao themeDao;
    private final TopStoryDao topStoryDao;
    private final UserInfoDao userInfoDao;
    private final SectionDao sectionDao;
    private final StoryDetailDao storyDetailDao;
    private final ReadHistoryDao readHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        creativeDaoConfig = daoConfigMap.get(CreativeDao.class).clone();
        creativeDaoConfig.initIdentityScope(type);

        storyDaoConfig = daoConfigMap.get(StoryDao.class).clone();
        storyDaoConfig.initIdentityScope(type);

        themeDaoConfig = daoConfigMap.get(ThemeDao.class).clone();
        themeDaoConfig.initIdentityScope(type);

        topStoryDaoConfig = daoConfigMap.get(TopStoryDao.class).clone();
        topStoryDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        sectionDaoConfig = daoConfigMap.get(SectionDao.class).clone();
        sectionDaoConfig.initIdentityScope(type);

        storyDetailDaoConfig = daoConfigMap.get(StoryDetailDao.class).clone();
        storyDetailDaoConfig.initIdentityScope(type);

        readHistoryDaoConfig = daoConfigMap.get(ReadHistoryDao.class).clone();
        readHistoryDaoConfig.initIdentityScope(type);

        creativeDao = new CreativeDao(creativeDaoConfig, this);
        storyDao = new StoryDao(storyDaoConfig, this);
        themeDao = new ThemeDao(themeDaoConfig, this);
        topStoryDao = new TopStoryDao(topStoryDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        sectionDao = new SectionDao(sectionDaoConfig, this);
        storyDetailDao = new StoryDetailDao(storyDetailDaoConfig, this);
        readHistoryDao = new ReadHistoryDao(readHistoryDaoConfig, this);

        registerDao(Creative.class, creativeDao);
        registerDao(Story.class, storyDao);
        registerDao(Theme.class, themeDao);
        registerDao(TopStory.class, topStoryDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(Section.class, sectionDao);
        registerDao(StoryDetail.class, storyDetailDao);
        registerDao(ReadHistory.class, readHistoryDao);
    }
    
    public void clear() {
        creativeDaoConfig.clearIdentityScope();
        storyDaoConfig.clearIdentityScope();
        themeDaoConfig.clearIdentityScope();
        topStoryDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
        sectionDaoConfig.clearIdentityScope();
        storyDetailDaoConfig.clearIdentityScope();
        readHistoryDaoConfig.clearIdentityScope();
    }

    public CreativeDao getCreativeDao() {
        return creativeDao;
    }

    public StoryDao getStoryDao() {
        return storyDao;
    }

    public ThemeDao getThemeDao() {
        return themeDao;
    }

    public TopStoryDao getTopStoryDao() {
        return topStoryDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public SectionDao getSectionDao() {
        return sectionDao;
    }

    public StoryDetailDao getStoryDetailDao() {
        return storyDetailDao;
    }

    public ReadHistoryDao getReadHistoryDao() {
        return readHistoryDao;
    }

}