package cn.ml.saddhu.bihudaily.engine.domain;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.ml.saddhu.bihudaily.engine.dbconverter.StringConverter;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STORY".
*/
public class StoryDao extends AbstractDao<Story, String> {

    public static final String TABLENAME = "STORY";

    /**
     * Properties of entity Story.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Images = new Property(0, String.class, "images", false, "IMAGES");
        public final static Property Date = new Property(1, String.class, "date", false, "DATE");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property Id = new Property(3, String.class, "id", true, "ID");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
        public final static Property Multipic = new Property(5, boolean.class, "multipic", false, "MULTIPIC");
        public final static Property TagName = new Property(6, String.class, "tagName", false, "TAG_NAME");
        public final static Property IsTag = new Property(7, boolean.class, "isTag", false, "IS_TAG");
    }

    private final StringConverter imagesConverter = new StringConverter();

    public StoryDao(DaoConfig config) {
        super(config);
    }
    
    public StoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STORY\" (" + //
                "\"IMAGES\" TEXT," + // 0: images
                "\"DATE\" TEXT," + // 1: date
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 3: id
                "\"TITLE\" TEXT," + // 4: title
                "\"MULTIPIC\" INTEGER NOT NULL ," + // 5: multipic
                "\"TAG_NAME\" TEXT," + // 6: tagName
                "\"IS_TAG\" INTEGER NOT NULL );"); // 7: isTag
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Story entity) {
        stmt.clearBindings();
 
        List images = entity.getImages();
        if (images != null) {
            stmt.bindString(1, imagesConverter.convertToDatabaseValue(images));
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(2, date);
        }
        stmt.bindLong(3, entity.getType());
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(4, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
        stmt.bindLong(6, entity.getMultipic() ? 1L: 0L);
 
        String tagName = entity.getTagName();
        if (tagName != null) {
            stmt.bindString(7, tagName);
        }
        stmt.bindLong(8, entity.getIsTag() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Story entity) {
        stmt.clearBindings();
 
        List images = entity.getImages();
        if (images != null) {
            stmt.bindString(1, imagesConverter.convertToDatabaseValue(images));
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(2, date);
        }
        stmt.bindLong(3, entity.getType());
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(4, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
        stmt.bindLong(6, entity.getMultipic() ? 1L: 0L);
 
        String tagName = entity.getTagName();
        if (tagName != null) {
            stmt.bindString(7, tagName);
        }
        stmt.bindLong(8, entity.getIsTag() ? 1L: 0L);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3);
    }    

    @Override
    public Story readEntity(Cursor cursor, int offset) {
        Story entity = new Story( //
            cursor.isNull(offset + 0) ? null : imagesConverter.convertToEntityProperty(cursor.getString(offset + 0)), // images
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // date
            cursor.getInt(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // title
            cursor.getShort(offset + 5) != 0, // multipic
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tagName
            cursor.getShort(offset + 7) != 0 // isTag
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Story entity, int offset) {
        entity.setImages(cursor.isNull(offset + 0) ? null : imagesConverter.convertToEntityProperty(cursor.getString(offset + 0)));
        entity.setDate(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTitle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMultipic(cursor.getShort(offset + 5) != 0);
        entity.setTagName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsTag(cursor.getShort(offset + 7) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(Story entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Story entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Story entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
